version: '3'

services:
  web:
    container_name: alpha
    restart: always
    build: .

    ports:
      - "8000:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
